name: code quaility

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

env:
  GO_VERSION: 1.16

jobs:
  mods:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: go mod tidy -v
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
